project_id = "rexjtzpuywmytxomlpwg"

[functions.chat]
verify_jwt = false

[functions.get-personality]
verify_jwt = false

[functions.check-toggle]
verify_jwt = false

[functions.get-customizations]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.fetch-vapi-voices]
verify_jwt = false

[functions.web-chat]
verify_jwt = false

[functions.start-vapi-call]
verify_jwt = false

[functions.generate-logo]
verify_jwt = false