project_id = "rexjtzpuywmytxomlpwg"

[functions.chat]
verify_jwt = true

[functions.get-personality]
verify_jwt = false

[functions.check-toggle]
verify_jwt = false

[functions.get-customizations]
verify_jwt = true

[functions.n8n-webhook]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.fetch-vapi-voices]
verify_jwt = true

[functions.web-chat]
verify_jwt = false

[functions.start-vapi-call]
verify_jwt = true

[functions.generate-logo]
verify_jwt = true

[functions.create-product-agent]
verify_jwt = true

[functions.upload-product-media]
verify_jwt = true

[functions.delete-product-agent]
verify_jwt = true

[functions.log-interaction]
verify_jwt = false

[functions.get-product-media]
verify_jwt = false

[functions.create-character]
verify_jwt = true

[functions.update-call-hector-assistant]
verify_jwt = true

[functions.vapi-call-webhook]
verify_jwt = false

[functions.product-chat]
verify_jwt = false

[functions.get-vapi-config]
verify_jwt = true

[functions.vapi-text-chat]
verify_jwt = true

[functions.generate-greeting]
verify_jwt = true

[functions.web-search]
verify_jwt = true

[functions.analyze-conversations]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false